var profiles = {
    chris: {
        id: 'chris',
        pw: 111,
        nick: 'chrispower',
        img: null,
        status: -1,
        friendsList: [],
        banList: [],
        socket_id: null,
    },
    paul: {
        id: 'paul',
        pw: 111,
        nick: 'paulpower',
        img: null,
        status: 0,
        friendsList: [],
        banList: [],
        socket_id: null,
    },
    tom: {
        id: 'tom',
        pw: 111,
        nick: 'cruz',
        img: null,
        status: 0,
        friendsList: [],
        banList: [],
        socket_id: null,
    },
    mary: {
        id: 'mary',
        pw: 111,
        nick: 'cruz',
        img: null,
        status: 0,
        friendsList: [],
        banList: [],
        socket_id: null,
    },
    jane: {
        id: 'jane',
        pw: 111,
        nick: 'cruz',
        img: null,
        status: 0,
        friendsList: [],
        banList: [],
        socket_id: null,
    },
    alice: {
        id: 'alice',
        pw: 111,
        nick: 'cruz',
        img: null,
        status: 0,
        friendsList: [],
        banList: [],
        socket_id: null,
    }
};
module.exports = profiles